# Generated by Django 3.0.8 on 2020-10-06 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aspy_election', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produit',
        ),
    ]
