# Generated by Django 3.1.2 on 2020-11-07 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspy_election', '0002_delete_produit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
