# Generated by Django 3.1.2 on 2020-11-23 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aspy_election', '0004_aspians'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aspians',
            new_name='Aspian',
        ),
    ]
